### PR TITLE
feat(tracing): Upgrade otel to 1.27

### PR DESCRIPTION
**Pull request by rossi99**
Upgrade otel to v1.27.0. Allows us to remove the following linter settings from repos:
```
# exclude deprecation warning for otelgrpc as there is no replacements yet
    # waiting for https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5196
    - linters:
        - staticcheck
      text: "SA1019: otelgrpc.WithInterceptorFilter is deprecated"
    - linters:
        - staticcheck
      text: "SA1019: otelgrpc.UnaryServerInterceptor is deprecated"
    - linters:
        - staticcheck
      text: "SA1019: otelgrpc.StreamServerInterceptor is deprecated"
```

### CODE REVIEW

**Comment by BradleyChatha** [comment]
Do we have a ticket about that deprecation, we'll need to go update our code to migrate those interceptors to [NewServerHandler](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc#NewServerHandler).

We'd probably also need to update the README at some point as well, since we refer to the interceptors there.

**Comment by BradleyChatha** [comment]
🤦 Yet again I get bamboozled by the Github email when I wasn't asked to review.

**Comment by rossi99** [comment]
> 🤦 Yet again I get bamboozled by the Github email when I wasn't asked to review.

Haha all good man, I'm just testing the waters with this one - just to see if its worth

**Comment by rossi99** [comment]
Implemented in `assetmanager.svc` on branch: refactor/tracing-kit-upgrade. Will MR it when this is merged

**Review by andypwarren — APPROVED** [review]

**Pull request merged**
